In [1]:
import numpy as np
from scipy.linalg import eigh

alpha = np.array([0.298073, 1.242567, 5.782948, 38.474970], dtype="float64")
c = np.array([0.25,0.25,0.25,0.25], dtype="float64")

In [2]:
Q = np.zeros((4,4,4,4))
S = np.zeros((4,4))
A = np.zeros((4,4))
T = np.zeros((4,4))
h = np.zeros((4,4))

# build Q
for p in range(4):
    for q in range(4):
        for r in range(4):
            for s in range(4):
                numQ = ( 2 * ((np.pi)**(5/2)) ) 
                denQ = ( alpha[p] + alpha [q] ) * ( alpha[r] + alpha[s] ) \
                * np.sqrt( alpha[p] + alpha [q] + alpha[r] + alpha[s])
                Q[p][r][q][s] = numQ/denQ
                
# build S
for p in range(4):
    for q in range(4):
        S[q][p] = ( np.pi / ( alpha[p] + alpha[q] ) ) ** (3/2)
            
# build T
for p in range(4):
    for q in range(4):
        T[p][q] = 3 * (( ( alpha[p]*alpha[q] )*( np.pi**(3/2) ) ) \
                        / ( ( alpha[p] + alpha[q] )**(5/2) ))
        
# build A
for p in range(4):
    for q in range(4):
        A[p][q] = - ( (2 * np.pi) / ( alpha[p] + alpha[q] ) )
        
# build h
for p in range(4):
    for q in range(4):
        h[p][q] = 2*A[p][q] + T[p][q]

In [3]:
# C normalization
def c_norm(c,S):
    NormSquared = c@S@c
    c = c/np.sqrt(NormSquared)
    return c

c = c_norm(c,S)

In [4]:
def build_F(h,Q,c):
    
    F = np.zeros((4,4))
    
    F1 = np.zeros((4,4))
    for p in range(4):
        for r in range(4):
            for q in range(4):
                for s in range(4):
                    F1[r][s] = Q[p][r][q][s]*c[r]*c[s]
    for p in range(4):
        for q in range(4):
            F[p][q] = F1[p][q] + h[p][q]
    print(F1)
    print(h)
    print(F)
    return F

def build_Eg(c,h,Q):
    
    Eg1 = 0
    Eg2 = 0
    
    for p in range(4):
        for r in range(4):
            for q in range(4):
                for s in range(4):
                    Eg1 = Eg1 + Q[p][r][q][s]*c[p]*c[q]*c[r]*c[s]
                    
    for p in range(4):
        for q in range(4):
            Eg2 = Eg2 + c[p]*c[q]*h[p][q]
            
    return Eg1 + 2 * Eg2    

In [5]:
E = 0.
new_E = 1000.

while( abs(E-new_E) > 1e-6 ):
    
    c = c_norm(eigenvectors[0], S)
    F = build_F(h,Q,c)
    print(F)
    
    E = new_E
    # Solve the generalized eigenvalue problem Fc = E'Sc
    eigenvalues, eigenvectors = \
    eigh(F, b=S, eigvals_only=False, overwrite_a=True, overwrite_b=True)
    sort_indices = np.argsort(eigenvalues)
    eigenvalues = eigenvalues[sort_indices]
    eigenvectors = eigenvectors[:, sort_indices]
    
    c = c_norm(eigenvectors[0], S)
    new_E = build_Eg(c,h,Q)


[[4.13180575e-03 1.58914136e-03 3.91449674e-04 5.20035240e-05]
 [1.58914136e-03 9.79301698e-04 3.36913274e-04 5.05609539e-05]
 [3.91449674e-04 3.36913274e-04 1.99334605e-04 4.45159968e-05]
 [5.20035240e-05 5.05609539e-05 4.45159968e-05 2.27219210e-05]]
[[-1.56704407e+01 -6.05651235e+00 -1.75071599e+00 -3.03635210e-01]
 [-6.05651235e+00 -2.40743875e+00 -8.71147177e-01 -2.36061536e-01]
 [-1.75071599e+00 -8.71147177e-01  1.41492399e-01  1.29567990e-03]
 [-3.03635210e-01 -2.36061536e-01  1.29567990e-03  3.12776396e-01]]
[[-1.56663089e+01 -6.05492321e+00 -1.75032454e+00 -3.03583207e-01]
 [-6.05492321e+00 -2.40645945e+00 -8.70810263e-01 -2.36010975e-01]
 [-1.75032454e+00 -8.70810263e-01  1.41691733e-01  1.34019589e-03]
 [-3.03583207e-01 -2.36010975e-01  1.34019589e-03  3.12799118e-01]]
[[-1.56663089e+01 -6.05492321e+00 -1.75032454e+00 -3.03583207e-01]
 [-6.05492321e+00 -2.40645945e+00 -8.70810263e-01 -2.36010975e-01]
 [-1.75032454e+00 -8.70810263e-01  1.41691733e-01  1.34019589e-03]
 [-3.035

In [6]:
result = build_Eg(c,h,Q)
print(result)

-2.691757208146355
